#! /usr/bin/env sh
set -xeuo pipefail

# make ssh key
open https://github.com/settings/keys
read -p "Create your ssh key for github, press entry when completed..."

# xcode
xcode-select --install ||:
read -p "Installing xcode, press enter when completed..."

# install brew
open https://brew.sh/
read -p "Install homebrew, press enter when completed..."

# install bash git and make
brew install bash git make glib-openssl
PATH="/opt/homebrew/bin:${PATH}"
hash -r

# workstation repo
mkdir -vp ~/repos
cd ~/repos
git clone git@github.com:hypergig/workstation.git
cd workstation
source config/.vars
hash -r

# install ansible
pip3 install --user --upgrade pip
pip3 install --user ansible jmespath

# install
exec make install
