# -*- ansible -*-
---
- hosts: 127.0.0.1
  connection: local
  module_defaults:
    homebrew:
      update_homebrew: yes
    homebrew_cask:
      update_homebrew: yes
      install_options: force
    apt:
      force_apt_get: yes
      cache_valid_time: 3600
    get_url:
      force: no
    pip:
      extra_args: --user
      state: latest
  vars:
    brew_prefix: "{{ lookup('pipe', 'brew --prefix') }}"
    special_playbooks:
    - "{{playbook_dir}}/playbooks/packages.yml"
    - "{{playbook_dir}}/playbooks/upgrade.yml"
    ordered_playbooks:
    - "{{special_playbooks.0}}"
    - "{{lookup('fileglob', 'playbooks/*.yml').split(',') | difference(special_playbooks)}}"
    - "{{special_playbooks.1}}"
    playbooks: "{{ordered_playbooks | flatten}}"
  tasks:
    - include_tasks: "{{playbook}}"
      with_items: "{{ app | default(playbooks)}}"
      loop_control:
        loop_var: playbook
  handlers:
    - name: Need to reboot
      debug:
        msg: Some tasks changed that may require a reboot for them to take affect
