# -*- ansible -*-
---
- hosts: 127.0.0.1
  connection: local
  module_defaults:
    apt:
      force_apt_get: yes
      cache_valid_time: 3600
    get_url:
      force: no
  vars:
    apps: "{{ app | default(lookup('fileglob', 'playbooks/*').split(',') | sort)}}"
  tasks:
    - include_tasks: "{{playbook}}"
      with_items: "{{apps}}"
      loop_control:
        loop_var: playbook
