theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", units = "imperial" }

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
ip = false
speed_up = true
#graph_up = true
speed_down = true
#graph_down = true
interval = 5

[[block]]
block = "custom"
command = "kubectl config current-context | cut -d'_' -f4"
interval = 60

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
device = "DisplayDevice"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "toggle"
text = "Scale"
command_state = "swaymsg -rt get_outputs | jq -r '.[] | select(.name == \"eDP-1\") | .scale' | grep 2"
command_on = "swaymsg output eDP-1 scale 2"
command_off = "swaymsg output  eDP-1 scale 1"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %l:%M %p"
