theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "custom"
command = "kubectl config current-context | cut -d'_' -f4"
interval = 60

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %l:%M %p"
