#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


echo "$(date) - starting load"

# global settings
yabai -m config auto_balance          on
yabai -m config split_ratio           .5
yabai -m config window_placement      second_child
yabai -m space --balance

# general space settings
yabai -m config layout                       bsp
yabai -m config window_gap                   06

# rules
yabai -m rule --add label='preferences' title='^.*Preferences.*$' manage='off'
yabai -m rule --add label='zoom' title='^Zoom$' app='^zoom.us$' manage='off'

echo "$(date) - yabai configuration loaded.."
