# -*- ansible -*-
---
- name: install apts
  apt:
    name:
    - apt-transport-https
    - bpython3
    - ca-certificates
    - curl
    - gnupg-agent
    - htop
    - jq
    - make
    - neofetch
    - pavucontrol
    - python-jmespath
    - python3-jmespath
    - python3-pip
    - software-properties-common
    - tree
    - vim
  become: true
  register: apts

- name: downloading debs
  get_url:
    url: "{{item}}"
    dest: "cache/{{item | basename}}"
    checksum: sha256:77c7627818630d73bedcfc0b38dde145d2554bea2d49616fe9b3cf8eb5f290db
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  register: downloads

- name: installing debs
  apt:
    deb: "{{item}}"
  with_items: "{{downloads.results | json_query('[*].dest')}}"
  become: true

- name: install snaps
  snap:
    name:
    - pycharm-community
    - code
    classic: true
  become: true
