# -*- ansible -*-
---
- name: add docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: true

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_facts.lsb.codename}} stable"
  become: true

- name: install docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: true

- name: install docker compose
  pip:
    name: docker-compose==1.24.1

- name: docker compose bash completion
  get_url:
    url:  https://raw.githubusercontent.com/docker/compose/1.24.1/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    checksum: sha256:dca94a0f3e5629dfabbb1a69785d0a812570704986f49e1b214f823bbb9a7dc3
  become: true

- name: add jordan to docker group
  user:
    name: jordan
    groups: docker
    append: yes
  become: true
