# -*- ansible -*-
---
- name: gcloud apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
  become: true

- name: add gcloud apt repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] {{item}}"
  with_items:
    - "https://packages.cloud.google.com/apt cloud-sdk main"
    - "https://apt.kubernetes.io/ kubernetes-xenial main"
  become: true

- name: install gcloud apts
  apt:
    name:
    - google-cloud-sdk
    - kubectl=1.17.4-00
  become: true

- name: kubernetes pip package
  pip:
    name: kubernetes

- name: download istio bins
  get_url:
    url: https://github.com/istio/istio/releases/download/1.5.0/istio-1.5.0-linux.tar.gz
    dest: cache/istio-1.5.0-linux.tar.gz
    checksum: sha256:fba603390074b1b9da9b3bd1492a278740fe725ac8ff07b8ec54fb7d66e03c33

- name: istioctl bin
  unarchive:
    dest: /usr/local/bin
    extra_opts:
    - --strip-components=2
    - istio-1.5.0/bin/istioctl
    remote_src: yes
    src: "{{playbook_dir}}/cache/istio-1.5.0-linux.tar.gz"
  become: true
