# -*- ansible -*-
---
- name: creating themes directory
  file:
    state: directory
    dest: ~/.themes

- name: cloning solarized theme
  git:
    repo: git@github.com:rtlewis88/rtl88-Themes.git
    depth: 1
    dest: ~/repos/rtl88-Themes
    version: Solarized-Dark-gtk-theme-colorpack

- name: linking themes
  file:
    state: link
    src: "{{item}}"
    dest: "~/.themes/{{item | basename}}"
  # filglob filter does not return directories
  with_lines: find /home/jordan/repos/rtl88-Themes -type d -maxdepth 1 -mindepth 1 -not -path '*/\.*'
