# -*- ansible -*-
---

- name: download joplin
  get_url:
    url: "{{url}}"
    dest: /usr/local/bin/joplin
    checksum: "sha512:{{ lookup('url', '{{url}}.sha512', split_lines=false) }}"
    mode: 0775
  vars:
    latest: "{{lookup('url', 'https://github.com/laurent22/joplin/releases/latest/download/latest-linux.yml', split_lines=false) | from_yaml}}"
    url: "https://github.com/laurent22/joplin/releases/download/v{{latest.version}}/{{latest.path}}"
  become: true

- name:  create desktop file
  copy:
    content: |
      [Desktop Entry]
      Encoding=UTF-8
      Name=Joplin
      Comment=Joplin for Desktop
      Exec=joplin
      Icon=joplin
      StartupWMClass=Joplin
      Type=Application
      Categories=Office
    dest: ~/.local/share/applications/appimagekit-joplin.desktop

- name: create icon directory
  file:
    state: directory
    dest: ~/.local/share/icons/hicolor/512x512/apps

- name: fetch joplin icon
  get_url:
    url: https://joplinapp.org/images/Icon512.png
    dest: ~/.local/share/icons/hicolor/512x512/apps/joplin.png
