# -*- ansible -*-
---
- name: download jsonnet bins
  get_url:
    url: https://github.com/google/jsonnet/releases/download/v0.15.0/jsonnet-bin-v0.15.0-linux.tar.gz
    dest: cache/jsonnet-bin-v0.15.0-linux.tar.gz
    checksum: sha256:f9575ae2dcd769bfe2475b86695387fc57d4b4fd60b0af2dee57f37091754370

- name: jsonnet bins
  unarchive:
    dest: /usr/local/bin
    remote_src: yes
    src: "{{playbook_dir}}/cache/jsonnet-bin-v0.15.0-linux.tar.gz"
  become: true
