# -*- ansible -*-
---
- name: install apts
  apt:
    name:
    - apt-transport-https
    - bpython3
    - ca-certificates
    - curl
    - gimp
    - flatpak
    - git
    - gnupg-agent
    - htop
    - jq
    - make
    - neofetch
    - net-tools
    - pavucontrol
    - python3-pip
    - python3-venv
    - software-properties-common
    - tree
    - vim
  become: true

- name: add flat remote
  command: flatpak remote-add -v --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  register: result
  changed_when: "'F: Imported 1 GPG key to remote \"flathub\"' in result.stderr"
  become: true

- name: install flatpaks
  flatpak:
    name: >
      us.zoom.Zoom
  register: result
  changed_when: "'Installation complete.' in result.stdout"

# debs need to be able to update them selves
- name: installing debs
  apt:
    deb: "{{item}}"
  with_items:
  - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- name: install snaps
  snap:
    name:
      - signal-desktop
  become: true

- name: install snaps (classic)
  snap:
    name:
    - code
    - go
    - goland
    - protobuf
    - pycharm-community
    - slack
    classic: true
  become: true

- name: install snaps (edge)
  snap:
    name:
    - node
    classic: true
    channel: latest/edge
  become: true

- name: install pips
  pip:
    name:
    - ansible
    - changelog-cli
    - click
    - dazl
    - fusepy
    - jmespath
    - pex
    - pip
    - progressbar
    - pycodestyle
    - semver
    - yq

- name: install npms
  npm:
    name: bats
    path: ~/.node
