# -*- ansible -*-
---
- name: brew pacakges
  homebrew:
    name:
      - coreutils
      - diffutils
      - direnv
      - docker-completion
      - docker-compose-completion
      - findutils
      - gnu-getopt
      - gnu-sed
      - gnu-tar
      - gnu-time
      - gnu-which
      - golang
      - htop
      - jq
      - make
      - node@14
      - tree
      - watch

- name: brew casks
  homebrew_cask:
    name:
      - google-chrome
      - intellij-idea
      - joplin
      - kap
      - menumeters
      - slack
      - spotify
      - sublime-text
      - typora
      - visual-studio-code
      - zoom

- name: install pips
  pip:
    name:
    - ansible 
    - jmespath
    - pip
