# -*- ansible -*-
---
- name: install apts
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - dconf-editor
    - direnv
    - flatpak
    - gnome-tweaks
    - gnupg-agent
    - htop
    - jq
    - make
    - neofetch
    - net-tools
    - openjdk-14-jdk
    - paprefs
    - pavucontrol
    - python3-pip
    - software-properties-common
    - tree
    - vim
  become: true

- name: add flat remote
  command: flatpak remote-add -v --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  register: result
  changed_when: "'F: Imported 1 GPG key to remote \"flathub\"' in result.stderr"
  become: true

# stubbed out for future use
# - name: install flatpaks
#   flatpak:
#     name: >
#       # us.stub.flatpak
#   register: result
#   changed_when: "'Installation complete.' in result.stdout"

- name: Create cache directory
  file:
    dest: "{{playbook_dir}}/cache"
    state: directory

# debs need to be able to update them selves
- name: installing debs
  apt:
    deb: "{{item}}"
  with_items:
  - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - https://zoom.us/client/latest/zoom_amd64.deb
  become: true

- name: install snaps
  snap:
    name:
    - gimp
    - spotify
  become: true

- name: install snaps (classic)
  snap:
    name:
    - code
    - go
    - goland
    - intellij-idea-ultimate
    - protobuf
    - pycharm-community
    - slack
    classic: true
  become: true

- name: install snaps (edge)
  snap:
    name:
    - node
    classic: true
    channel: latest/edge
  become: true

- name: install pips
  pip:
    name:
    - ansible
    - dazl
    - jmespath
    - pip
    - pycodestyle
    - yq

- name: install npms
  npm:
    name: bats
    path: ~/.node
