# -*- ansible -*-
---
- name: brew pacakges
  homebrew:
    name:
      - coreutils
      - diffutils
      - direnv
      - findutils
      - gnu-getopt
      - gnu-sed
      - gnu-tar
      - gnu-time
      - gnu-which
      - golang
      - htop
      - jq
      - make
      - node

- name: brew casks
  homebrew_cask:
    name:
      - google-chrome
      - intellij-idea 
      - slack
      - spotify
      - sublime-text
      - zoom

- name: install pips
  pip:
    name:
    - ansible
    - jmespath
    - pip