# -*- ansible -*-
---
- name: install apts
  apt:
    name:
    - apt-transport-https
    - bpython3
    - ca-certificates
    - curl
    - gimp
    - git
    - gnupg-agent
    - htop
    - jq
    - make
    - neofetch
    - pavucontrol
    - python3-pip
    - python3-venv
    - software-properties-common
    - tree
    - vim
  become: true

- name: downloading debs
  get_url:
    url: "{{item.url}}"
    dest: "cache/{{item.url | basename}}"
    checksum: "sha256:{{item.sha256}}"
  with_items:
  - url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sha256: 85e07dee624d3c7eec6a6194efcb070b353ee52c0e5980517760230128a3ba61
  - url: https://zoom.us/client/latest/zoom_amd64.deb
    sha256: 069afc06abdd6e5534c417e8e92fb7167ed023df06ab10110b759ff8b56f5e3a
  register: downloads

- name: installing debs
  apt:
    deb: "{{item}}"
  with_items: "{{downloads.results | json_query('[*].dest')}}"
  become: true

- name: install snaps
  snap:
    name:
      - signal-desktop
  become: true

- name: install snaps (classic)
  snap:
    name:
    - code
    - go
    - goland
    - protobuf
    - pycharm-community
    - slack
    classic: true
  become: true

- name: install snaps (edge)
  snap:
    name:
    - node
    classic: true
    channel: latest/edge
  become: true

- name: install pips
  pip:
    name:
    - ansible
    - changelog-cli
    - click
    - dazl
    - fusepy
    - jmespath
    - pex
    - pip
    - poetry
    - progressbar
    - pycodestyle
    - semver
    - yq

- name: install npms
  npm:
    name: bats
    path: ~/.node
