# -*- ansible -*-
---
- name: install apts
  apt:
    name:
    - apt-transport-https
    - bpython3
    - ca-certificates
    - curl
    - git
    - gnupg-agent
    - htop
    - jq
    - make
    - neofetch
    - pavucontrol
    - python3-pip
    - software-properties-common
    - tree
    - vim
  become: true

- name: downloading debs
  get_url:
    url: "{{item.url}}"
    dest: "cache/{{item.url | basename}}"
    checksum: "sha256:{{item.sha256}}"
  with_items:
  - url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sha256: eb9dfc7bb27ca6373fd51e7a1daeac59cd6dd2600431861710bed160208bcf37
  - url: https://zoom.us/client/latest/zoom_amd64.deb
    sha256: e52fb0e6754ff25dd16635d77bbe38a11389f07fa69d4c5063f76d00ebd11ed7
  register: downloads

- name: installing debs
  apt:
    deb: "{{item}}"
  with_items: "{{downloads.results | json_query('[*].dest')}}"
  become: true

- name: install snaps
  snap:
    name:
    - code
    - go
    - goland
    - protobuf
    - pycharm-community
    classic: true
  become: true

- name: install snaps (edge)
  snap:
    name:
    - node
    classic: true
    channel: latest/edge
  become: true

- name: install pips
  pip:
    name:
    - ansible
    - changelog-cli
    - click
    - dazl
    - fusepy
    - jmespath
    - pip
    - pipenv
    - progressbar
    - pycodestyle
    - PyYAML
    - semver
    - yq

- name: install npms
  npm:
    name: bats
    path: ~/.node
