# -*- ansible -*-
---
- name: install python apps
  apt:
    name:
    - bpython3
  become: true

- name: clone pyenv repo
  git:
    repo: git://github.com/yyuu/pyenv.git
    dest: ~/repos/pyenv

- name: link pyenv
  file:
    state: link
    src: ~/repos/pyenv
    dest: ~/.pyenv
