# -*- ansible -*-
---
- name: add regolith repo
  apt_repository:
    repo: "ppa:regolith-linux/release"
  become: true

- name: install regolith
  apt:
    name:
    - dunst
    - imwheel
    - regolith-desktop
    - regolith-look-solarized-dark
    # for xfce4-panel
    - xfce4-battery-plugin
    - xfce4-cpugraph-plugin
    - xfce4-genmon-plugin
    - xfce4-mpc-plugin
    - xfce4-netload-plugin
    - xfce4-panel
    - xfce4-pulseaudio-plugin
    - xfce4-sensors-plugin
    - xfce4-statusnotifier-plugin
    - xfce4-systemload-plugin
    - xfce4-weather-plugin
  become: true

- name: yank rofication package
  apt:
    name: regolith-rofication
    state: absent
  become: true

- name: Create config directories
  file:
    dest: ~/.config/regolith/i3
    state: directory

- name: link regolith configs
  file:
    state: link
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
  - src: "{{playbook_dir}}/config/Xresources"
    dest: ~/.config/regolith/Xresources
  - src: "{{playbook_dir}}/config/i3.config"
    dest: ~/.config/regolith/i3/config
  - src: "{{playbook_dir}}/config/.imwheelrc"
    dest: ~/.imwheelrc

- name: setting look
  shell: regolith-look set solarized-dark && regolith-look refresh || echo "look is already set"
  register: result
  changed_when: "'look is already set' not in result.stdout"
