# -*- ansible -*-
---
- name: add regolith repo
  apt_repository:
    repo: "ppa:regolith-linux/release"
  become: true

- name: install regolith
  apt:
    name:
    - regolith-desktop
    - regolith-look-solarized-dark
  become: true

- name: link regolith configs
  file:
    state: link
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
  - src: "{{playbook_dir}}/config/Xresources"
    dest: ~/.config/regolith/Xresources
  - src: "{{playbook_dir}}/config/i3.config"
    dest: ~/.config/regolith/i3/config

- name: setting look
  shell: regolith-look set solarized-dark && regolith-look refresh || echo "look is already set"
  register: result
  changed_when: "'look is already set' not in result.stdout"
