# -*- ansible -*-
---
- name: add regolith repo
  apt_repository:
    repo: "ppa:regolith-linux/release"
  become: true

- name: install regolith
  apt:
    name:
    - regolith-desktop
    - regolith-look-solarized-dark
  become: true

- name: link alacritty config
  file:
    state: link
    src: "{{playbook_dir}}/config/Xresources"
    dest: ~/.config/regolith/Xresources

- name: setting look
  shell: regolith-look set solarized-dark && regolith-look refresh || echo "look is already set"
  register: result
  changed_when: "'look is already set' not in result.stdout"
