# -*- ansible -*-
---
- name: signal apt key
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
  become: true

- name: add signal apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
  become: true

- name: install signal apts
  apt:
    name: signal-desktop
  become: true
