# -*- ansible -*-
---
- name: add spotify repo key
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
  become: true

- name: add spotify repo
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
  become: true

- name: install spotify
  apt:
    name: spotify-client
  become: true
