# -*- ansible -*-
---
- name: add sublime repo key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
  become: true

- name: add sublime repo
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
  become: true

- name: install sublime
  apt:
    name: sublime-text
  become: true
