# -*- ansible -*-
---
- name: install sway, wayland tools, and prereqs
  apt:
    name:
    - brightnessctl
    - grim
    - rofi
    - slurp
    - sway
    - sway-backgrounds
    - swaybg
    - swayidle
    - swaylock
    - wl-clipboard
    # prereqs for waybar (as per 19.10)
    - fonts-font-awesome
    - libgtkmm-3.0-dev
    - libjsoncpp-dev
    - libinput-dev
    - libsigc++-2.0-dev
    - libpulse-dev
    - libnl-3-dev
    - libdbusmenu-gtk3-dev
    - libnl-genl-3-dev
    - libfmt-dev
    - clang-tidy
    - libmpdclient-dev
    - libwayland-dev
    - libgtk-3-dev
    - gobject-introspection
    - libgirepository1.0-dev
    - scdoc
    # prereqs for mako
    - libsystemd-dev
  become: true

- name: link sway config
  file:
    state: link
    src: "{{playbook_dir}}/config/sway/config.d"
    dest: /etc/sway/config.d
  become: true

- name: add jordan to video group so he can control brightness
  user:
    name: jordan
    groups: video
    append: yes
  become: true

- name: clone waybar repo
  git:
    repo: git@github.com:Alexays/Waybar.git
    dest: ~/repos/Waybar

- name: build waybar
  shell: meson build && ninja -C build
  args:
    chdir: ~/repos/Waybar
  register: result
  changed_when: "'ninja: no work to do.' not in result.stdout"

- name: install waybar
  shell: ninja -C build install
  args:
    chdir: /home/jordan/repos/Waybar
  become: true
  changed_when: result.changed

- name: linking waybar config
  file:
    state: link
    src:  "{{playbook_dir}}/config/waybar"
    dest:  ~/.config/waybar

- name: clone mako repo
  git:
    repo: git@github.com:emersion/mako.git
    dest: ~/repos/mako

- name: build mako
  shell: meson build && ninja -C build
  args:
    chdir: ~/repos/mako
  register: result
  changed_when: "'ninja: no work to do.' not in result.stdout"

- name: install mako
  shell: ninja -C build install
  args:
    chdir: /home/jordan/repos/mako
  become: true
  changed_when: result.changed
