# -*- ansible -*-
---
- name: install terminal tools
  homebrew:
    name:
      - bash
      - bash-completion@2
      - rust

- name: pull alacritty repo
  git:
    repo: git@github.com:alacritty/alacritty.git
    version: v0.9.0
    dest: ~/repos/alacritty
  register: result

- name: build alacritty
  make:
    target: app
    chdir: ~/repos/alacritty
  when: result is changed

- name: create alacritty app
  synchronize:
    src: ~/repos/alacritty/target/release/osx/Alacritty.app
    dest: /Applications

- name: create alacritty config dir
  file:
    state: directory
    dest: ~/.config/alacritty

- name: link alacritty config
  file:
    state: link
    src: "{{playbook_dir}}/config/alacritty.yml"
    dest: ~/.config/alacritty/alacritty.yml

- name: add brew bash as shell
  lineinfile:
    path: /etc/shells
    line: "{{brew_prefix}}/bin/bash"
  become: true

- name: set brew brash as default shell
  shell: |
    [ "${SHELL}" == {{brew_prefix}}/bin/bash ] && echo 'shell is good' || chsh -s {{brew_prefix}}/bin/bash
  register: result
  changed_when: "'shell is good' not in result.stdout"

- name: bash profile
  file:
    state: link
    src: "{{playbook_dir}}/config/{{item}}"
    dest: "~/{{item}}"
  with_items:
    - .bash_profile
    - .vars
