# -*- ansible -*-
---
- name: add alacritty repo
  apt_repository:
    repo: "ppa:mmstick76/alacritty"
  become: true

- name: install alacritty
  apt:
    name: alacritty
  become: true

- name: create alacritty config dir
  file:
    state: directory
    dest: ~/.config/alacritty

- name: link alacritty config
  file:
    state: link
    src: "{{playbook_dir}}/config/alacritty.yml"
    dest: ~/.config/alacritty/alacritty.yml
