# -*- ansible -*-
---
- name: upgrade all brews
  homebrew:
    upgrade_all: yes

- name: upgrade all casks
  homebrew_cask:
    upgrade_all: yes

- name: upgrade pips
  pip:
    name: "{{lookup('lines', 'pip3 list --user --outdated --not-required --format=freeze | cut -d= -f1')}}"
